### ISSUE TITLE
No Feedback for error cases

### ISSUE THREAD

**Issue by Alex-Michie** [izenn/padbox#5] opened 2019-09-28 19:33 UTC
It appears that when there is an error decoding json that the site just continues along as if nothing happened in error and will provide links for where you should get directed to if your box was setup properly, or at least i believe this was what happened.

Here is what i did when attempted to use the site you've hosted.

First (since i had it on hand) i tried uploading an old json dump from padherder proxy i had, from 2018, and everything worked well, box was populated and i was happy.
Then seeing that things appeared to work i made a new dump and tried to import it, and it instantly gave me a link to my box instead of the processing time it took last time, and nothing appeared to be different.
Finally to sort of check that i haven't made an error in assuming how things worked i tried uploading the new json dump to a user id one off from my own that happened to not exist yet and checked to see if it was an issue with updating or something else and it again passed thru instantly to the next screen providing links to the box data i uploaded except both of these links 404'd.

If it helps with determining the actual error for why this failed the id 312725317 was the one i used to test, and i am pretty sure i have the most recent padherder proxy, so i don't think that would be the issue... but i am open to helping figure out what caused the actual error as well

**Comment by izenn** [comment] 2019-09-28 20:03
i had a similar error happen to me the other day.  I'm actively looking into this

**Comment by izenn** [comment] 2019-09-28 20:17
please try again, it looks like the recaptcha was causing issues.  I have modified the submit code to hopefully work around the issues.  I'll keep this open until i hear back from you.  thanks!

**Comment by Alex-Michie** [comment] 2019-09-28 21:23
Appears to be still happening, both on my actual id (no change on upload) and on the other one which still appears to be totally unused (i did get a captcha this time though, none of my attempts till now got me one)

no error messages or anything to suggest everything didnt go perfectly either

**Comment by izenn** [comment] 2019-09-28 22:35
not sure why error logging is not working properly, i'll investigate that as well.  could you post your current json so i can test with your data?  I don't want to assume that the one that is uploaded is the most recent.

thanks!

**Comment by Alex-Michie** [comment] 2019-09-28 22:46
[captured_data.txt](https://github.com/izenn/padbox/files/3666085/captured_data.txt)
this is the one ive been trying to upload (i hope there arent any api keys in there, thruthfully i dont know much about its format yet)

**Comment by izenn** [comment] 2019-09-28 22:52
running it locally in my dev environment i'm getting an error:
Nested quantifiers in regex; marked by <-- HERE in m/([0-9]{1,4} )** <-- HERE ***/ at ./pad.pl line 416.

this is a good thing, because now i can dig in and fix it.

Thanks for providing your json.  After we get your json working, i'll be adding debug output into the submission script (shouldn't be too hard, just need to get the php to capture and display stdout)

**Comment by Alex-Michie** [comment] 2019-09-28 22:56
awesome, and thanks for making this, im really looking forward to using this :D

**Comment by izenn** [comment] 2019-09-28 22:59
potential fix has been uploaded, i ran it locally using your data and the box seemed to be generated properly.  Please test and let me know one way or another.

**Comment by Alex-Michie** [comment] 2019-09-28 23:10
yes everything updated perfectly, thank you so much

**Comment by izenn** [comment] 2019-09-28 23:11
cool -- i'm just working on fixing one regression that my fix caused (current evo is not bolding properly)  once i get that fixed i'll close this issue

**Comment by izenn** [comment] 2019-09-28 23:19
fixed in 17c73cd

**Closed as completed by izenn** 2019-09-28 23:19 UTC

**Comment by Alex-Michie** [comment] 2019-09-29 00:18
i think this still may be an issue, i leveled up a creature , updated my box, didnt see any changes, possibly since it was in the materials tab?

but then i made it a helper lead to see if it would be recognized at all, and now it doesnt act like its succeeding, but also leaves the /results.php page a solid white, and i get a http 500

i believe this just means there isnt a page setup to get served on a 500 error but i havent really touched php before

[captured_data.txt](https://github.com/izenn/padbox/files/3666153/captured_data.txt)
json in case thats helpful to look at for the actual error

**Comment by izenn** [comment] 2019-09-29 00:19
yeah, i'm in the middle of doing an update to get debug logging on the results.php -- it is going a bit sideways.  i'm reverting and moving to a test environment now
